### ISSUE TITLE
Hello, could you please let me know whether the value of "Hiou" is greater than one or less than one? Is there a potential error in Formula 6 as presented in the paper? Does it conflict with the description in Figure Four?

### ISSUE THREAD

**Issue by ydhexyk** [ymzis69/HybridSORT#12]
Hello, could you please let me know whether the value of "Hiou" is greater than one or less than one? Is there a potential error in Formula 6 as presented in the paper? Does it conflict with the description in Figure Four?

**Comment by ymzis69** [comment]
"Hiou" takes values within the range [0, 1), as the denominator is always greater than the numerator. According to our examination, Equation 6 does not have apparent errors and corresponds to Figure 4. If you have any questions, you can refer to our code implementation. Our code implementation serves as the most accurate reference.
