### ISSUE TITLE
The problem still exists. How long will it take for this bug to be fixed？

### ISSUE THREAD

**Issue by liguo668** [ymzis69/HybridSORT#14]
Sorry, this was our mistake because we uploaded the wrong version of README.md. Please run the code according to this version of the README.md: https://github.com/ymzis69/HybirdSORT/tree/6101e1b225cb4b860f914049f9cccc0cd4538075, as ‘yolox_dancetrack_val_Hybrid_sort.py’ is not present in our exp file. We will have this bug fixed within the next two days. We apologize again for any inconvenience this may have caused you.

_Originally posted by @ymzis69 in https://github.com/ymzis69/HybirdSORT/issues/13#issuecomment-1702393530_

**Comment by ymzis69** [comment]
The current repository has fixed the issue of running command errors.
