### ISSUE TITLE
The parameters are not used?

### ISSUE THREAD

**Issue by llfortune** [ymzis69/HybridSORT#16]
yolox.core.trainer:before_train:124 - args: Namespace(experiment_name='yolox_x_ablation', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, exp_file='exps/example/mot/yolox_x_ablation.py', resume=False, ckpt=None, start_epoch=21, num_machines=1, machine_rank=0, fp16=True, occupy=False, opts=['fp16', '-o', '-c', 'pretrained/yolox_x.pth', '--resume', '/home/ubuntu/HybridSORT/YOLOX_outputs/yolox_x_ablation/last_epoch_ckpt.pth.tar'])
    this is log, the parameters in opts do not work?

**Comment by ymzis69** [comment]
Yes, our code is based on YOLOX and OCSORT, and there are some parameters that are not used but originate from YOLOX and OCSORT.

**Comment by llfortune** [comment]
Thanks，I have solved it.
