### ISSUE TITLE
About the use of detectors

### ISSUE THREAD

**Issue by lyhisneo** [ymzis69/HybridSORT#17]
hello, this is a wonderful work! I read the code for the trace process in detail, but ran into a problem. what should I do if I want to use the ckt_file variable in the image below? What detector did you use to get the data? Looking forward to your reply.
Best wishes.
![image](https://github.com/ymzis69/HybridSORT/assets/151700247/2770758b-a7a8-48b3-8f92-39925d8df529)

**Comment by HanGuangXin** [comment]
Thanks for your interest in our work!
The code in the image employs a trick to enhance the speed of inferencing (**NOTE that this trick is not used for the FPS metric in the paper. The FPS metric includes both detection and association, and optionally reid part**). It achieves this by locally loading detection results and reid embeddings. More specifically, we store the detections and embeddings obtained from the detector and reid model mentioned in the paper. Later, we can load these results from the local storage of the images, effectively reducing the latency of feature extraction and enabling faster inference.
If the ckp_file exists, we can simply load the stored results and bypass the detection and reid feature extraction steps. Alternatively, we can follow the standard procedure of detection and reid feature extraction as usual.

Please feel free to reach out if you have any additional questions or my response doesn't fully address your concerns.

**Comment by lyhisneo** [comment]
Thank you very much, my problem has been solved.

**Comment by David1-git** [comment]
我的代码报错说数据纬度不匹配，我猜测是不是因为我没有ckt_file文件？

**Comment by ymzis69** [comment]
@David1-git 数据维度不匹配可能是numpy或者pytorch版本的原因，有一些数据可能多一个维度或者少一个维度，您可以debug一下，使用unsqueeze或者squeeze这种函数修改数据的维度。
