### ISSUE TITLE
Retrieving lost tracklet information

### ISSUE THREAD

**Issue by Mohit-robo** [ymzis69/HybridSORT#19]
Hey, great work. I wanted some information regarding the lost tracks. 
Referring to BoTSORT implementation, [here](https://github.com/NirAharon/BoT-SORT/blob/251985436d6712aaf682aaaf5f71edb4987224bd/tracker/bot_sort.py#L425) you can see that lost tracklet information can also be used if required. 
Coming to HybridSORT, I see [here](https://github.com/ymzis69/HybridSORT/blob/95f289520638b44ae00616e68da43447445fb7d0/trackers/hybrid_sort_tracker/hybrid_sort.py#L555) you are removing the dead tracklets. Do these two things mean the same, if so, can I use the dead tracklet information assuming it is the lost tracklet as in BOT-SORT's case?

**Comment by ymzis69** [comment]
Hello, our algorithm also uses the lost tracklet for tracking. [here](https://github.com/ymzis69/HybridSORT/blob/95f289520638b44ae00616e68da43447445fb7d0/trackers/hybrid_sort_tracker/hybrid_sort.py#L555) means that the time for the lost tracklet to disappear exceeds max_ age (30 frames) will be removed, corresponding to the lost tracklet in BoT-SORT becoming removed_ Tracks ([here](https://github.com/NirAharon/BoT-SORT/blob/251985436d6712aaf682aaaf5f71edb4987224bd/tracker/bot_sort.py#L461)).

**Comment by Mohit-robo** [comment]
Thanks for the reply, that is what I wanted to confirm.
