### ISSUE TITLE
What does train/val/test_segmap mean?

### ISSUE THREAD

**Issue by juechenzp** [ymzis69/HybridSORT#21]
![image](https://github.com/ymzis69/HybridSORT/assets/38826329/c61162c6-36e1-4da5-8792-d45c1c5a9116)
Thank you for your work. Could tell me what does the test_segmap or val_segmap mean in DanceTrackDataset, which not appear in OC-Sort.

**Comment by ymzis69** [comment]
This is the collection of video sequence names gathered for computing the HOTA metric on the dancetrack dataset. These files can be downloaded from the dancetrack repository: https://github.com/DanceTrack/DanceTrack/tree/main/dancetrack
