### ISSUE TITLE
Adjusting max_age parameter

### ISSUE THREAD

**Issue by Mohit-robo** [ymzis69/HybridSORT#22]
Hey, we had a discussion last time in this [issue](https://github.com/ymzis69/HybridSORT/issues/19). 
I doubted the `max_age` parameter. Just wanted to know the value `30` is 30 frames if I am not wrong. If so how can I adjust the final removal of lost tracks according to the FPS of the incoming stream? I have another value of FPS for the incoming stream.

**Comment by ymzis69** [comment]
Yes, the value 30 represents 30 frames. I may have some misunderstanding of your question, but you can directly modify the parameters [here](https://github.com/ymzis69/HybridSORT/blob/95f289520638b44ae00616e68da43447445fb7d0/trackers/hybrid_sort_tracker/hybrid_sort.py#L285) regardless of the FPS of your input video.

**Comment by Mohit-robo** [comment]
Okay thanks
