### ISSUE TITLE
Question about the publication of the paper

### ISSUE THREAD

**Issue by NVRGUP** [ymzis69/HybridSORT#23]
How soon will Hybrid-SORT be published in AAAI?

**Comment by ymzis69** [comment]
The AAAI 2024 conference is scheduled to take place from February 20th to 27th, 2024. Hybrid-SORT will be published shortly thereafter.

**Comment by ymzis69** [comment]
Our paper has been published at https://ojs.aaai.org/index.php/AAAI/article/view/28471.
