### ISSUE TITLE
关于用自己的数据集训练detector的问题

### ISSUE THREAD

**Issue by ljcmhw** [ymzis69/HybridSORT#25]
您好，我想请教一下iou_loss和cls_loss的计算代码是在什么位置呀？我目前使用自己的数据集执行training时这两个数据始终为0.并且best AP也为0。非常感谢

**Comment by ymzis69** [comment]
IoU_oss: [here](https://github.com/ymzis69/HybridSORT/blob/master/yolox/models/yolo_head.py#L399) and 
cls_loss: [here](https://github.com/ymzis69/HybridSORT/blob/master/yolox/models/yolo_head.py#L405)

**Comment by ljcmhw** [comment]
Ok，thank you!
