### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SylviaCL** [ymzis69/HybridSORT#27]
首先对大佬的工作点赞加拜服！科研小菜鸡求问大佬，我没有训练dectector，直接进行tracking，但是为什么总是报segmentation fault (core dumped)错误啊，搜了很多解决方案都不太可，望大佬空闲时能指点指点。谢谢大佬啦！
![Snipaste_2024-04-14_11-55-35](https://github.com/ymzis69/HybridSORT/assets/44056945/f1614a27-1eeb-465d-924c-4b974c753606)

**Comment by ymzis69** [comment]
这个问题基本上是因为您的运行环境有问题，或许您需要重新配置您的代码运行环境。

**Comment by SylviaCL** [comment]
> 这个问题基本上是因为您的运行环境有问题，或许您需要重新配置您的代码运行环境。

好的，感谢大佬！祝大佬科研、生活顺利~
