### ISSUE TITLE
MOT20-test

### ISSUE THREAD

**Issue by Zc229** [ymzis69/HybridSORT#28]
![屏幕截图 2024-05-06 150033](https://github.com/ymzis69/HybridSORT/assets/127744968/b7056487-8922-44aa-b5fe-1c15c202417a)
This error occurs when I am testing MOT20, tools/run_hybrid_sort_dance.py. May I ask what is the problem?

**Comment by ymzis69** [comment]
Hello, specific metrics for the MOT20 test need to be submitted to the MOTChallenge website. The error you encountered is specific to testing tracking metrics. May I ask which command you ran?

**Comment by Zc229** [comment]
> 您好，MOT20测试的具体指标需要提交到MOTchallenge网站。您遇到的错误特定于测试跟踪指标。请问你运行的是哪个命令？

Thank you very much for your answer. I haven't found a solution to the problem yet. I'm running this command 'python tools/run_hybrid_sort_dance.py -f exps/example/mot/yolox_x_mix_mot20_ch_hybrid_sort.py -b 1 -d 1 --fuse  --mot20 --expn $exp_name ’

**Comment by ymzis69** [comment]
ok, maybe you can put [train.txt](https://github.com/ymzis69/HybridSORT/files/15248819/train.txt) in this path: /MOT20/seqmaps/.

**Comment by Zc229** [comment]
> ok, maybe you can put [train.txt](https://github.com/ymzis69/HybridSORT/files/15248819/train.txt) in this path: /MOT20/seqmaps/.

ok,Thank you for your help！

**Comment by Zc229** [comment]
> > ok, maybe you can put [train.txt](https://github.com/ymzis69/HybridSORT/files/15248819/train.txt) in this path: /MOT20/seqmaps/.
> 
> ok,Thank you for your help！

hi，I have a new question. When I want to verify dancetrack, Run  python tools/run_hybrid_sort_dance.py -f exps/example/mot/yolox_dancetrack_val_hybrid_sort.py -b 1 -d 1 --fp16 --fuse --expn $exp_name indicates the error
![image](https://github.com/ymzis69/HybridSORT/assets/127744968/c0efc551-0fd0-4e9d-8676-b679fcc23043)
What is the reason for this?

**Comment by ymzis69** [comment]
This error occurred because the program couldn't find your result file (dancetrack0004.txt is a result file), hence it couldn't compute the metrics. You may need to adjust the corresponding path in the program according to where your inference results are saved.

**Comment by Zc229** [comment]
> This error occurred because the program couldn't find your result file (dancetrack0004.txt is a result file), hence it couldn't compute the metrics. You may need to adjust the corresponding path in the program according to where your inference results are saved.

Is this file dancetrack0004.txt generated because my data set is formatted incorrectly? I did not generate the file dancetrack0004.txt.

**Comment by ymzis69** [comment]
Yes, you are right, dancetrack0004.txt is not a generated test file. Perhaps I need more information from you, otherwise I don't know what this error is about. Are you able to generate test results correctly when you run this program?
