### ISSUE TITLE
Skip loading parameter 'heads.veight' to the model

### ISSUE THREAD

**Issue by Nxhhhh** [ymzis69/HybridSORT#29]
Hello, when I was trying to run '--demo_type image -f G:/pycharmprojects/pythonProject/HybridSORT-master/exps/example/mot/yolox_x_mix_mot20_ch_hybrid_sort_reid.py -c G:/pycharmprojects/pythonProject/HybridSORT-master/pretrained/ocsort_x_mot20.pth.tar --path
E:/datasets/MOT20/test/MOT20-04/img1 --fuse --save_result'
a warning occured.
![微信图片_20240508110338](https://github.com/ymzis69/HybridSORT/assets/148049582/cd420f05-85f2-453a-83ad-083e8ec716f2)
I don't know why this warning occurs, how to solve it.

**Comment by ymzis69** [comment]
Reference this [issue](https://github.com/ymzis69/HybridSORT/issues/4). If the model can track objects, you can ignore this warming.
