### ISSUE TITLE
How can we use official YOLOX as the detector?

### ISSUE THREAD

**Issue by yaoshanliang** [ymzis69/HybridSORT#30]
I trained a weight from the official YOLOX (https://github.com/Megvii-BaseDetection/YOLOX), and put it in the `self.ckpt`. However, when I run the evaluation code using `run_hybrid_sort_dance.py`, the generated detection results are empty. It works well when I used the trained weight using `tools/train.py` from HybridSORT.

Can we use the trained weight from official YOLOX? Or some other modifications should be made.

**Comment by ymzis69** [comment]
Hello, our weights are derived from [ByteTrack](https://github.com/ifzhang/ByteTrack) and [OC-SORT](https://github.com/noahcao/OC_SORT), trained on a pedestrian dataset with only one class, whereas the official YOLOX weights are trained on 80 classes. Our code currently does not support multi-class tracking. If you need to perform multi-class tracking, perhaps you can refer to this repository: https://github.com/CaptainEven/MCMOT-ByteTrack.
