### ISSUE TITLE
为什么ReID的提升效果这么好？

### ISSUE THREAD

**Issue by fenguan** [ymzis69/HybridSORT#32]
你好，请问ReID的提升效果好是因为使用了更先进的ReID还是什么原因呢。我想加入到我的方法中。谢谢

**Comment by fenguan** [comment]
我的困惑在于最近的方法中如bytetrack，ocsort中好像并没有ReID，是不是因为加入了效果变差

**Comment by ymzis69** [comment]
可能对于每种跟踪方法，添加ReID模块的效果并不太一致。根据我们的实验观察，对于一些比较复杂、非线性运动比较多的跟踪数据集，ReID模块对模型跟踪性能的提升还是很多的。对于ocsort算法，根据我们的实验观察，添加ReID模块在Dancetrack数据集上的跟踪性能提升是比较明显的。
