### ISSUE TITLE
hybrid_sort.py

### ISSUE THREAD

**Issue by fneaplle** [ymzis69/HybridSORT#33]
Hi there. I really appreciate your great job.

While i'm read your code, I find some trouble in your code.

https://github.com/ymzis69/HybridSORT/blob/396f8d30db13304c0cbaf1dcf2e16ded93ce1701/trackers/hybrid_sort_tracker/hybrid_sort.py#L341

I think this line need to be change to
```
trk[:] = [pos[0][0], pos[0][1], pos[0][2], pos[0][3], kalman_score[0], simple_score[0]]
```

Because trackers.predict function returns List of kalman scores.

@ymzis69

**Comment by ymzis69** [comment]
Hi, our program runs normally in our environment. It seems that different versions of numpy cause the returned data format to be inconsistent, so you can modify this code as long as it ensures that the code runs correctly.

**Comment by fneaplle** [comment]
> Hi, our program runs normally in our environment. It seems that different versions of numpy cause the returned data format to be inconsistent, so you can modify this code as long as it ensures that the code runs correctly.

I didn't realize that the numpy version was different. Thanks for your reply. I hope you have a nice day :blush:
