### ISSUE TITLE
Unable to reproduce the dancetrack effect in the paper

### ISSUE THREAD

**Issue by levi5611** [ymzis69/HybridSORT#34]
Why is the result of the dancetrack-test I reproduced 65.2, far from the 65.7 in the paper? Is there something wrong?

**Comment by ymzis69** [comment]
The results of the HOTA metric test are not fixed; outcomes between 65.2 and 65.7 are all possible.

**Comment by levi5611** [comment]
So the disparity in these results is dependent on what? Is it the different scores on each target test?（所以这些结果的差距是取决于什么？是每次目标检测的分数不一样吗？）

**Comment by ymzis69** [comment]
This might depend on the calculation method of HOTA. Different machines may result in slight variations in detection and tracking outcomes, such as the scores of the bounding boxes and the regression accuracy of the boxes. If you are interested in the HOTA metric calculation method, you can refer to the original paper: https://arxiv.org/pdf/2009.07736.

**Comment by levi5611** [comment]
Ok, I see, thanks for the answer
