### ISSUE TITLE
Kalman filter

### ISSUE THREAD

**Issue by WangZhuping123** [ymzis69/HybridSORT#35]
The paper mentions that the width varies more dramatically than the height, indicating that the aspect ratio is changing. Why, when using the Kalman filter, is the state vector represented as (u,v,s,c,r) with the assumption that r remains constant, instead of using 
(u,v,w,h) and their rates of change?

**Comment by ymzis69** [comment]
Our paper is modified based on OCSORT, so we only added the variable s on top of the Kalman filter used in OCSORT. You could try using the format (u,v,w,h) for the Kalman filter to see if it yields better results.
